const daftarKata = [
    // [Kata Mayoritas, Kata Impostor, Kategori]
    // KATEGORI: MAKANAN & MINUMAN
    ["Nasi Goreng", "Nasi Uduk", "Makanan"],
    ["Bakso", "Soto", "Makanan"],
    ["Sate Ayam", "Sate Kambing", "Makanan"],
    ["Pizza", "Burger", "Fast Food"],
    ["KFC", "McDonalds", "Brand Makanan"],
    ["Ramen", "Mie Ayam", "Makanan"],
    ["Kopi", "Teh", "Minuman"],
    ["Susu", "Yogurt", "Minuman"],
    ["Coca Cola", "Pepsi", "Minuman"],
    ["Es Cream", "Gelato", "Makanan"],
    ["Donat", "Roti", "Camilan"],
    ["Martabak Manis", "Terang Bulan", "Camilan"],
    ["Siomay", "Batagor", "Jajanan"],
    ["Cilok", "Cimol", "Jajanan"],
    ["Indomie", "Mie Sedap", "Brand"],
    ["Kripik Kentang", "Kripik Singkong", "Camilan"],
    ["Kebab", "Burger", "Makanan"],
    ["Soto Ayam", "Sop Ayam", "Makanan"],
    ["Bubur Ayam", "Lontong Sayur", "Sarapan"],
    ["Cokelat", "Permen", "Manisan"],

    // KATEGORI: NEGARA & KOTA
    ["Indonesia", "Malaysia", "Negara"],
    ["Singapura", "Brunei", "Negara"],
    ["Jepang", "Korea Selatan", "Negara"],
    ["China", "Taiwan", "Negara"],
    ["Inggris", "Amerika", "Negara"],
    ["Prancis", "Italia", "Negara"],
    ["Arab Saudi", "Uni Emirat Arab", "Negara"],
    ["Brasil", "Argentina", "Negara"],
    ["Rusia", "Ukraina", "Negara"],
    ["Australia", "Selandia Baru", "Negara"],
    ["Jakarta", "Surabaya", "Kota"],
    ["Bandung", "Bogor", "Kota"],
    ["Yogyakarta", "Solo", "Kota"],
    ["Bali", "Lombok", "Wisata"],
    ["Mekkah", "Madinah", "Kota Suci"],
    ["London", "Paris", "Kota"],
    ["Tokyo", "Seoul", "Kota"],
    ["New York", "Los Angeles", "Kota"],
    ["Semarang", "Purwokerto", "Kota"],
    ["Thailand", "Vietnam", "Negara"],

    // KATEGORI: ARTIS & TOKOH
    ["Raffi Ahmad", "Baim Wong", "Artis"],
    ["Deddy Corbuzier", "Raditya Dika", "YouTuber"],
    ["Justin Bieber", "Shawn Mendes", "Penyanyi"],
    ["Ariana Grande", "Taylor Swift", "Penyanyi"],
    ["Cristiano Ronaldo", "Lionel Messi", "Atlet"],
    ["Neymar", "Mbappe", "Atlet"],
    ["Jokowi", "Prabowo", "Tokoh"],
    ["Atta Halilintar", "Ria Ricis", "YouTuber"],
    ["Blackpink", "Twice", "Grup Kpop"],
    ["BTS", "Exo", "Grup Kpop"],
    ["Tom Cruise", "Brad Pitt", "Aktor"],
    ["Iron Man", "Captain America", "Superhero"],
    ["Batman", "Superman", "Superhero"],
    ["Naruto", "Sasuke", "Anime"],
    ["Luffy", "Zoro", "Anime"],
    ["Doraemon", "Shinchan", "Kartun"],
    ["Upin", "Ipin", "Kartun"],
    ["Mr. Beast", "PewDiePie", "YouTuber"],
    ["Agnez Mo", "Anggun C. Sasmi", "Penyanyi"],
    ["Iwan Fals", "Slank", "Musisi"],

    // KATEGORI: BENDA & TEKNOLOGI
    ["Laptop", "Komputer", "Elektronik"],
    ["Smartphone", "Tablet", "Elektronik"],
    ["iPhone", "Android", "HP"],
    ["Televisi", "Monitor", "Elektronik"],
    ["Keyboard", "Mouse", "Aksesori Komputer"],
    ["Kamera", "Handycam", "Alat Potret"],
    ["Earphone", "Headphone", "Audio"],
    ["Playstation", "Xbox", "Konsol"],
    ["Nintendo Switch", "Steam Deck", "Konsol"],
    ["Kulkas", "Freezer", "Alat Rumah Tangga"],
    ["AC", "Kipas Angin", "Alat Rumah Tangga"],
    ["Mesin Cuci", "Mesin Pengering", "Alat Rumah Tangga"],
    ["Sapu", "Pel", "Alat Kebersihan"],
    ["Buku", "Majalah", "Media Cetak"],
    ["Pensil", "Pulpen", "Alat Tulis"],
    ["Penghapus", "Tip-X", "Alat Tulis"],
    ["Meja", "Kursi", "Furnitur"],
    ["Kasur", "Sofa", "Furnitur"],
    ["Jam Tangan", "Gelang", "Aksesori"],
    ["Kacamata", "Lensa Kontak", "Aksesori"],

    // KATEGORI: TRANSPORTASI & BRAND
    ["Mobil", "Motor", "Kendaraan"],
    ["Bus", "Kereta Api", "Transportasi Umum"],
    ["Pesawat", "Helikopter", "Transportasi Udara"],
    ["Kapal Laut", "Perahu", "Transportasi Air"],
    ["Gojek", "Grab", "Ojek Online"],
    ["Toyota", "Honda", "Brand Mobil"],
    ["Ferrari", "Lamborghini", "Mobil Mewah"],
    ["Tesla", "BYD", "Mobil Listrik"],
    ["Yamaha", "Suzuki", "Brand Motor"],
    ["Sepeda", "Skuter", "Kendaraan"],
    ["Nike", "Adidas", "Brand Sepatu"],
    ["Puma", "Reebok", "Brand Sepatu"],
    ["Gucci", "Louis Vuitton", "Brand Fashion"],
    ["H&M", "Zara", "Brand Fashion"],
    ["Samsung", "Apple", "Brand Tech"],
    ["Xiaomi", "Oppo", "Brand Tech"],
    ["Asus", "MSI", "Brand Laptop"],
    ["Indomaret", "Alfamart", "Minimarket"],
    ["Shopee", "Tokopedia", "E-commerce"],
    ["Instagram", "TikTok", "Sosial Media"],

    // KATEGORI: HEWAN & ALAM
    ["Kucing", "Anjing", "Hewan"],
    ["Harimau", "Singa", "Hewan Buas"],
    ["Gajah", "Zebra", "Hewan"],
    ["Sapi", "Kambing", "Hewan Ternak"],
    ["Ayam", "Bebek", "Unggas"],
    ["Burung Elang", "Burung Hantu", "Burung"],
    ["Ikan Cupang", "Ikan Guppy", "Ikan Hias"],
    ["Ikan Hiu", "Ikan Paus", "Hewan Laut"],
    ["Ular", "Cacing", "Hewan Melata"],
    ["Kupu-kupu", "Lebah", "Serangga"],
    ["Matahari", "Bulan", "Benda Langit"],
    ["Bumi", "Mars", "Planet"],
    ["Bintang", "Meteor", "Angkasa"],
    ["Gunung", "Bukit", "Alam"],
    ["Laut", "Danau", "Air"],
    ["Hujan", "Salju", "Cuaca"],
    ["Hutan", "Taman", "Alam"],
    ["Mawar", "Melati", "Bunga"],
    ["Pohon Kelapa", "Pohon Pinus", "Tumbuhan"],
    ["Bawang Merah", "Bawang Putih", "Bumbu"],

    // KATEGORI: OLAHRAGA & GAMES
    ["Sepak Bola", "Futsal", "Olahraga"],
    ["Basket", "Voli", "Olahraga"],
    ["Badminton", "Tenis Meja", "Olahraga"],
    ["Renang", "Menyelam", "Olahraga"],
    ["Lari", "Jalan Santai", "Olahraga"],
    ["Mobile Legends", "Honor of Kings", "Game Mobile"],
    ["PUBG", "Free Fire", "Game Battle Royale"],
    ["Minecraft", "Roblox", "Game Sandbox"],
    ["FIFA", "eFootball", "Game Bola"],
    ["Valorant", "Counter Strike", "Game FPS"],
    ["Genshin Impact", "Honkai Star Rail", "Game RPG"],
    ["Among Us", "Fall Guys", "Game Kasual"],
    ["Chess", "Checkers", "Permainan Papan"],
    ["Monopoli", "Ludo", "Permainan Papan"],
    ["Kartu Uno", "Kartu Remi", "Permainan"],
    ["Tinju", "Karate", "Bela Diri"],
    ["Gym", "Yoga", "Kesehatan"],
    ["Manchester United", "Liverpool", "Klub Bola"],
    ["Real Madrid", "Barcelona", "Klub Bola"],
    ["NBA", "Euroleague", "Liga Basket"],

    // KATEGORI: PEKERJAAN & SEKOLAH
    ["Dokter", "Perawat", "Profesi"],
    ["Guru", "Dosen", "Profesi"],
    ["Pilot", "Nakhoda", "Profesi"],
    ["Polisi", "Tentara", "Profesi"],
    ["Koki", "Pelayan", "Profesi"],
    ["Arsitek", "Insinyur", "Profesi"],
    ["Programmer", "Data Scientist", "Profesi"],
    ["Matematika", "Fisika", "Pelajaran"],
    ["Biologi", "Kimia", "Pelajaran"],
    ["Sejarah", "Geografi", "Pelajaran"],
    ["SD", "SMP", "Sekolah"],
    ["SMA", "Kuliah", "Pendidikan"],
    ["Ujian", "Tugas", "Sekolah"],
    ["Seragam", "Baju Bebas", "Pakaian"],
    ["Tas", "Ransel", "Benda"],
    ["Kantor", "Pabrik", "Tempat Kerja"],
    ["Pasar", "Mall", "Tempat Belanja"],
    ["Rumah Sakit", "Puskesmas", "Kesehatan"],
    ["Bandara", "Stasiun", "Transportasi"],
    ["Hotel", "Apartemen", "Tempat Tinggal"],

    // KATEGORI: CAMPURAN
    ["Gitar", "Bass", "Alat Musik"],
    ["Piano", "Keyboard Musik", "Alat Musik"],
    ["Drum", "Kendang", "Alat Musik"],
    ["Biola", "Cello", "Alat Musik"],
    ["Suling", "Terompet", "Alat Musik"],
    ["Keris", "Pedang", "Senjata"],
    ["Pistol", "Senapan", "Senjata"],
    ["Payung", "Jas Hujan", "Perlengkapan"],
    ["Dompet", "Tas Kecil", "Wadah"],
    ["Koper", "Ransel", "Wadah"],
    ["Sabun", "Sampo", "Mandi"],
    ["Sikat Gigi", "Pasta Gigi", "Mandi"],
    ["Handuk", "Selimut", "Kain"],
    ["Topi", "Helm", "Kepala"],
    ["Jaket", "Sweater", "Pakaian"],
    ["Kemeja", "Kaos", "Pakaian"],
    ["Celana Jeans", "Celana Bahan", "Pakaian"],
    ["Rok", "Daster", "Pakaian"],
    ["Batik", "Kebaya", "Budaya"],
    ["Wayang", "Gamelan", "Budaya"]
];